services:
  - type: web
    name: avtoozapchast
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEMO_MODE
        value: "false"
      - key: HEAD_ADMIN_ID
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: SHOP_NAME
        value: "Auto Sklad & Ehtiyot Qismlar"
